
package Frame;

import AppPackage.AnimationClass;
import controllers.altadeclientes.controladorCFP;
import controllers.altadeclientes.usuarios;
import internos.interno1;
import internos.tickets.print.Funciones;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    Funciones func = new Funciones();
    controladorCFP controlInserts = new controladorCFP();
    usuarios u = new usuarios();
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPNewUser.setVisible(false);
        jPanel1.setVisible(true);
        jDateChooser1.setDate(cargafecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlabelMusica = new javax.swing.JLabel();
        jlabelInternet = new javax.swing.JLabel();
        jlabelCalculadora = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPNewUser = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellid = new javax.swing.JTextField();
        txtCorre = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtpass1 = new javax.swing.JPasswordField();
        txtpass2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jpIngreso.setPreferredSize(new java.awt.Dimension(290, 580));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("PASSWORD");
        jpIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 110, 30));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("USER");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jpIngreso.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 170, 40));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 220, 20));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(187, 187, 187));
        jPasswordField1.setBorder(null);
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jpIngreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 170, 40));

        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_customer_32px_1.png"))); // NOI18N
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Key_32px.png"))); // NOI18N
        jpIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 120, 40));

        jlabelMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IconNewUser.png"))); // NOI18N
        jlabelMusica.setToolTipText("Crea usuario nuevo");
        jlabelMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelMusicaMouseClicked(evt);
            }
        });
        jpIngreso.add(jlabelMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 180, -1, 50));

        jlabelInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_32px.png"))); // NOI18N
        jlabelInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelInternetMouseClicked(evt);
            }
        });
        jpIngreso.add(jlabelInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, -1, 50));

        jlabelCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        jlabelCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelCalculadoraMouseClicked(evt);
            }
        });
        jpIngreso.add(jlabelCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 130, -1, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo1.png"))); // NOI18N
        jpIngreso.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("SISTEMA ADMINISTRATIVO DCR");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 580, 50));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tel: 249 42 5 05 59");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 320, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Central de Abastos Unión Benito Juárez");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 390, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Bodega No. 23, área de Tomate y Calabaza");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 320, 40));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 530));

        jPNewUser.setBackground(new java.awt.Color(255, 255, 255));
        jPNewUser.setPreferredSize(new java.awt.Dimension(760, 530));
        jPNewUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("NUEVO USUARIO");
        jPNewUser.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Repita contraseña:");
        jPNewUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nombre(s):");
        jPNewUser.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPNewUser.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Correo:");
        jPNewUser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Telefono:");
        jPNewUser.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Usuario:");
        jPNewUser.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Contraseña:");
        jPNewUser.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, 40));

        txtApellid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtApellid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 40));

        txtCorre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtCorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, 40));

        txtTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 130, 40));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, 40));

        jButton2.setBackground(new java.awt.Color(238, 112, 82));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPNewUser.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, 50));
        jPNewUser.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 40));

        txtpass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, 40));

        txtpass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPNewUser.add(txtpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, 40));

        jLayeredPane1.add(jPNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 580, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, jlabelInternet);
        
        AnimationClass calc = new AnimationClass();
        calc.jLabelXRight(-40, 10, 10, 5, jlabelCalculadora);
        
        AnimationClass music = new AnimationClass();
        music.jLabelXRight(-40, 10, 10, 5, jlabelMusica);
        /*    */
        AnimationClass internett = new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, jlabelInternet);
        
        AnimationClass calcu = new AnimationClass();
        calcu.jLabelXLeft(10, -40, 10, 5, jlabelCalculadora);
        
        AnimationClass musica = new AnimationClass();
        musica.jLabelXLeft(10, -40, 10, 5, jlabelMusica);
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
       // int dialog = JOptionPane.YES_NO_OPTION;
        //int result = JOptionPane.showConfirmDialog(null, "Desea salir de login","Exit",dialog);
        //if(result == 0){
            System.exit(0);
        //}
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jlabelInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelInternetMouseClicked
    openInternet();
    }//GEN-LAST:event_jlabelInternetMouseClicked

    private void jlabelCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelCalculadoraMouseClicked
        try{
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        }   catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabelCalculadoraMouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
    int var = evt.getKeyCode();
    if(var == KeyEvent.VK_ENTER){
        jButton1.doClick();
    }

    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jlabelMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelMusicaMouseClicked
    Object code = ""; 
         code = JOptionPane.showInputDialog(null,"Ingrese codigo para crear nuevo usuario");
    if(code.toString().isEmpty() || code == null){
        System.out.println("vacion");
    }else{
            if(code.equals("dcrpass123")){
                jPNewUser.setVisible(true);
                jPanel1.setVisible(false);
                limpiaCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Codigo incorrecto");
                jPNewUser.setVisible(false);
                jPanel1.setVisible(true);
            }
  }
    }//GEN-LAST:event_jlabelMusicaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List<String> contentL = new ArrayList<String>();
        String var1 = txtNombre.getText(),
                var2 = txtApellid.getText(),
                var3 = txtCorre.getText(),
                var4 = txtTel.getText(),
                var5 = txtUser.getText(),
                var6 = txtpass1.getText(),
                var7 = txtpass2.getText(),
                var8 = func.getFecha(jDateChooser1);
        if (var1.isEmpty() && var5.isEmpty() && var5.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar por lo menos campo Nombre o Usuario");
        } else {
            contentL.add((var1.isEmpty()) ? "/" : var1);
            contentL.add((var2.isEmpty()) ? "/" : var2);
            contentL.add((var5.isEmpty()) ? "/" : var5);
            contentL.add((var3.isEmpty()) ? "/" : var3);
            contentL.add((var4.isEmpty()) ? "/" : var4);
            if(var6.isEmpty() || var7.isEmpty()){
                JOptionPane.showMessageDialog(null, "Campos de contraseña no pueden ser vacios");
            }else{
                if(var6.equals(var7)){
                    contentL.add(u.MD5(var6));
                    contentL.add(var8);
                    controlInserts.insertaCamposUsers(contentL);
                    limpiaCampos();
                }else{
                    JOptionPane.showMessageDialog(null, "Contraseña no es la misma");
                }
            }
               
        }      
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = jTextField1.getText(),
            pass=jPasswordField1.getText();
                
           if(controlInserts.validaLoginUsers(user,u.MD5(pass))){
               
               interno1 vP = new interno1();
               vP.setVisible(true);
               vP.setEnabled(true);
               vP.validate();
               vP.cargaUser(user);
                this.dispose();
//               JOptionPane.showMessageDialog(null, "Login corrceto");
           }else{
               JOptionPane.showMessageDialog(null, "Login incorrecto");               
           }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void openInternet(){
        try{
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        }catch (IOException e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

        private Date cargafecha() {
        Date fechaAct = new Date();
        return fechaAct;
    }
        
        private void limpiaCampos(){
            txtNombre.setText("");
            txtApellid.setText("");
            txtCorre.setText("");
            txtTel.setText("");
            txtUser.setText("");
            txtpass1.setText("");
            txtpass2.setText("");
            jDateChooser1.setDate(cargafecha());
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPNewUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlabelCalculadora;
    private javax.swing.JLabel jlabelInternet;
    private javax.swing.JLabel jlabelMusica;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JTextField txtApellid;
    private javax.swing.JTextField txtCorre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField txtpass1;
    private javax.swing.JPasswordField txtpass2;
    // End of variables declaration//GEN-END:variables
}