/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author A. Rafael Notario Rodriguez
 */
public class VentaPiso extends javax.swing.JFrame {

    /**
     * Creates new form VentaPiso
     */
    Float monto;
    String folio;
    public VentaPiso(float monto, String folio) {
        initComponents();
        this.monto = monto;
        this.folio = folio;
        jPanContadoPay.setVisible(false);
        jPanCreditPay.setVisible(false);
        jPanReferenciaPay.setVisible(false);
        jLabACobrar.setText(Float.toString(monto));
    }

    public VentaPiso() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabCreditPay = new javax.swing.JLabel();
        jLabContadoPay = new javax.swing.JLabel();
        jLabReferPay = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabACobrar = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanCreditPay = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanContadoPay = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jLabel14 = new javax.swing.JLabel();
        jPanReferenciaPay = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venta de Piso");
        setBackground(new java.awt.Color(204, 204, 255));
        setName("frameVentasPiso"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabCreditPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabCreditPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/credito.png"))); // NOI18N
        jLabCreditPay.setToolTipText("CREDITO");
        jLabCreditPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabCreditPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabCreditPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabCreditPayMouseClicked(evt);
            }
        });
        jPanel1.add(jLabCreditPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, 50));

        jLabContadoPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabContadoPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cash.png"))); // NOI18N
        jLabContadoPay.setToolTipText("EFECTIVO");
        jLabContadoPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabContadoPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabContadoPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabContadoPayMouseClicked(evt);
            }
        });
        jPanel1.add(jLabContadoPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 50));

        jLabReferPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabReferPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transfer.png"))); // NOI18N
        jLabReferPay.setToolTipText("TRANSFERENCIA/TARJETA/OTRO");
        jLabReferPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabReferPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabReferPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabReferPayMouseClicked(evt);
            }
        });
        jPanel1.add(jLabReferPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 60, 50));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("TOTAL A COBRAR:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 40));

        jLabACobrar.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabACobrar.setForeground(new java.awt.Color(51, 0, 204));
        jLabACobrar.setText("3456.00");
        jPanel1.add(jLabACobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 50));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("METODO DE PAGO:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        jLayeredPane1.setBackground(new java.awt.Color(204, 255, 255));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanCreditPay.setBackground(new java.awt.Color(255, 255, 255));
        jPanCreditPay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pago a Credito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanCreditPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("CLIENTE:");
        jPanCreditPay.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"25", "GREGORIO", "MARTINEZ"},
                {"27", "DON VICTOR", "ROBLES JIMENEZ"},
                {"28", "TOMAS", "CARRASCO SORIA"},
                {"30", "AMADO", null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDOS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanCreditPay.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 90));

        jLayeredPane1.add(jPanCreditPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 190));

        jPanContadoPay.setBackground(new java.awt.Color(255, 255, 255));
        jPanContadoPay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pago a Contado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanContadoPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("PAGO CON:");
        jPanContadoPay.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("CAMBIO:");
        jPanContadoPay.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 30));
        jPanContadoPay.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, 30));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("134.00");
        jPanContadoPay.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 30));

        jLayeredPane1.add(jPanContadoPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 200));

        jPanReferenciaPay.setBackground(new java.awt.Color(255, 255, 255));
        jPanReferenciaPay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referencia de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanReferenciaPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanReferenciaPay.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 320, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NOTA:");
        jPanReferenciaPay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanReferenciaPay.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 250, 80));

        jLayeredPane1.add(jPanReferenciaPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 180));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 460, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 460, 420));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payMethod.png"))); // NOI18N
        jButton2.setText("Cobrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ARTICULOS:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, 40));

        jLabel17.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("4");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 140, 400));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 204));
        jLabel15.setText("COBRAR VENTA");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jPanContadoPay.isVisible()){
            JOptionPane.showMessageDialog(null,"Pago al contado");
        }else if(jPanCreditPay.isVisible()){
            JOptionPane.showMessageDialog(null,"Pago con credito");
        }else if(jPanReferenciaPay.isVisible()){
            JOptionPane.showMessageDialog(null,"Pago con referencia");
        }else{
            JOptionPane.showMessageDialog(null,"Elija metodo de pago");
        }
        
        jPanContadoPay.setVisible(false);
        jPanCreditPay.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabContadoPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabContadoPayMouseClicked
        jPanContadoPay.setVisible(true);
        jPanCreditPay.setVisible(false);
        jPanReferenciaPay.setVisible(false);
    }//GEN-LAST:event_jLabContadoPayMouseClicked

    private void jLabCreditPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabCreditPayMouseClicked
       jPanContadoPay.setVisible(false);
       jPanCreditPay.setVisible(true);  
       jLabReferPay.setVisible(false);
    }//GEN-LAST:event_jLabCreditPayMouseClicked

    private void jLabReferPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabReferPayMouseClicked
        jLabReferPay.setVisible(true);
        jPanContadoPay.setVisible(false);
        jPanCreditPay.setVisible(false);
    }//GEN-LAST:event_jLabReferPayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaPiso(18981,"45").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabACobrar;
    private javax.swing.JLabel jLabContadoPay;
    private javax.swing.JLabel jLabCreditPay;
    private javax.swing.JLabel jLabReferPay;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanContadoPay;
    private javax.swing.JPanel jPanCreditPay;
    private javax.swing.JPanel jPanReferenciaPay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
